server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    path: '/'
management:
  endpoint:
    health:
      show-details: always
      time-to-live: 60000ms
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  servlet:
    multipart:
      max-request-size: '10MB'
      max-file-size: '10MB'